### ISSUE TITLE
Raumfilter Problemseite

### ISSUE THREAD

**Issue by H3R0M0** [SchulIT/servicecenter#42]
Nutzt man den Raumfilter auf der Problemseite hat man anschließend nicht die Möglichkeit alle Räume (bzw. keinen Raum) auszuwählen ohne den Filter zurückzusetzen, da sonst eine Fehlermeldung ausgegeben wird. Gleiches geschieht wenn man am Raumfilter nichts ändert und beispielsweise nur Wartungsarbeiten mit einbeziehen möchte.

Zudem wird der Placeholder des Filters nicht angezeigt.

![image](https://user-images.githubusercontent.com/71940049/134773244-c30e5bd3-13c3-4f42-ae06-786447070e6f.png)

**Comment by frostieDE** [comment]
Ich schaffe es auch nur über eklige Umwege, dass der Platzhalter angezeigt wird :-/
