### ISSUE TITLE
Wartungsarbeit auf Dashboard anzeigen

### ISSUE THREAD

**Issue by Wiwaltill** [SchulIT/servicecenter#56]
In der Problemliste (Neue Probleme) auf dem Dashboard wird kein Badge bei einer Wartungsarbeit angezeigt. Dieses sieht man lediglich auf der Probleme-Page.

**Comment by H3R0M0** [comment]
Auf dem Dashboard kann (logischerweise) kein Badge für Wartungsarbeiten angezeigt werden, da Wartungsarbeiten allgemein nicht auf dem Dashboard angezeigt werden.

**Comment by Wiwaltill** [comment]
War mir nicht bewusst.
